name: Publish package to NPM registry

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: "package.json"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@caedes"
      - run: yarn --frozen-lockfile
      - run: yarn build
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
